# Generated by Django 3.1.3 on 2020-11-07 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('serial', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=120)),
                ('num_sessions_allowed', models.IntegerField(default=1)),
                ('expire_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('sub_type', models.CharField(choices=[('Monthly', 1), ('Third Month', 2), ('Yearly', 3)], default='1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='key_handler.key')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='key_handler.key')),
            ],
        ),
    ]
