# Generated by Django 3.1.3 on 2020-11-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_handler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='num_sessions_allowed',
        ),
    ]
