# Generated by Django 3.1.3 on 2020-11-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_handler', '0002_remove_key_num_sessions_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='num_sessions_allowed',
            field=models.IntegerField(default=1),
        ),
    ]
