# Generated by Django 3.1.3 on 2020-11-07 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_handler', '0003_key_num_sessions_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='session',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 19, 50, 16, 101349)),
        ),
        migrations.AddField(
            model_name='session',
            name='remote_session_id',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
