# Generated by Django 3.1.3 on 2020-11-07 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_handler', '0004_auto_20201107_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='key',
            old_name='serial',
            new_name='license_key',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='key',
            new_name='license_key',
        ),
        migrations.AlterField(
            model_name='session',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 19, 52, 16, 369796)),
        ),
    ]
