# Generated by Django 3.1.3 on 2020-11-07 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_handler', '0006_auto_20201107_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='key',
            name='email',
        ),
        migrations.RemoveField(
            model_name='session',
            name='expires',
        ),
        migrations.AddField(
            model_name='session',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 19, 58, 58, 804961)),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
