# Generated by Django 3.1.3 on 2020-11-07 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_handler', '0007_auto_20201107_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 20, 1, 54, 600516)),
        ),
    ]
